[package]
name = "ddns_cloudflare"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advmac = "1.0.3"
clap = { version = "4.2.7", features = ["derive"] }
directories = "5.0.1"
local-ip-address = "0.5.3"
mac_address2 = "2.0.0"
reqwest = { version = "0.11.17", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }
toml = "0.7.3"
