[package]
name = "ddns_cloudflare"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
directories = "4.0.1"
local-ip-address = "0.5.1"
reqwest = { version = "0.11.14", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["full"] }
toml = "0.7.2"
