[package]
name = "ddns_cloudflare"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
directories = "5.0.1"
local-ip-address = "0.5.4"
mac_address = "1.1.5"
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.7.4"
