[toolchain]
channel = "nightly"
components = ["clippy", "rustfmt"]
profile = "minimal"
targets = [
	"aarch64-unknown-linux-gnu",
	"x86_64-pc-windows-gnu",
	"x86_64-unknown-freebsd",
	"x86_64-unknown-linux-gnu",
]
